apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f4p0mk31s-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f4p0mk31s-nodejs 
  name: f4p0mk31s-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: f4p0mk31s-nodejs 
